services:
  nginx:
    image: nginx:alpine
    container_name: rpx-sjc
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site/:/etc/nginx/conf.d/
      - ./ssl/:/etc/ssl/
      - /usr/share/nginx/html/:/usr/share/nginx/html/
      - /usr/share/nginx/html/doe_empui/storage:/usr/share/nginx/html/doe_empui/storage:rw
      - /var/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: php74
    volumes:
      - /usr/share/nginx/html/:/usr/share/nginx/html/
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      - /var/log/php-fpm:/var/log/php-fpm
      - /etc/localtime:/etc/localtime
      - /var/log:/var/log
    environment:
      - PORT=9000
    deploy:
      replicas: 16
    restart: unless-stopped

networks:
  default:
    name: skill-matrix
    external: true
