name: datalake

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    networks:
      - internal
    volumes:
      - ./config/:/etc/gitlab-runner/
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - internal
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-cors.conf:/etc/nginx/cors.conf
      - ../data:/var/www/html
    depends_on:
      - memcached

  php-56:
    build:
      context: ../
      dockerfile: docker/php56
    environment:
      - PORT=9000
      - CI_ENV=development
    deploy:
      replicas: 4
    mem_limit: 4096m
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./php-56.ini:/usr/local/etc/php/php.ini
      - ../data:/var/www/html
  
  php-74:
    build:
      context: ../
      dockerfile: docker/php74
    environment:
      - PORT=9000
      - CI_ENV=development
    deploy:
      replicas: 4
    mem_limit: 4096m
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./php-56.ini:/usr/local/etc/php/php.ini
      - ../data:/var/www/html

  memcached:
    container_name: memcached
    image: memcached:alpine
    restart: unless-stopped
    ports:
      - 11211:11211
    networks:
      - internal
    
networks:
  internal:
    driver: bridge
